name: Semgrep Checks

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - internal/**
      - .semgrep.yml
      - .semgrep-service-name*yml

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: semgrep
      uses: returntocorp/semgrep-action@v1
  naming_semgrep0:
    name: Semgrep Naming Scan A-C,EC2
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.action != 'dependabot[bot]')
    steps:
    - uses: actions/checkout@v3
    - run: semgrep -c .semgrep-service-name0.yml
  naming_semgrep1:
    name: Semgrep Naming Scan C-G
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.action != 'dependabot[bot]')
    steps:
    - uses: actions/checkout@v3
    - run: semgrep -c .semgrep-service-name1.yml
  naming_semgrep2:
    name: Semgrep Naming Scan G-Q
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.action != 'dependabot[bot]')
    steps:
    - uses: actions/checkout@v3
    - run: semgrep -c .semgrep-service-name2.yml
  naming_semgrep3:
    name: Semgrep Naming Scan Q-Z
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.action != 'dependabot[bot]')
    steps:
    - uses: actions/checkout@v3
    - run: semgrep -c .semgrep-service-name3.yml
